name: Test Import Script

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test-import-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Set up Shell Test Env
        run: sudo apt-get install -y jq

      - name: Setup terragrunt
        uses: metro-digital/cf-github-actions/terragrunt-setup@v1

      - name: Install Just
        uses: extractions/setup-just@v3

      - name: Just install
        uses: extractions/setup-just@v3
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Cargo build
        #run: cargo build --all --all-features # this will also build the example projects, which are currently broken
        run: cargo build

      - name: Cargo test
        #run: cargo build --all --all-features # this will also build the example projects, which are currently broken
        run: cargo test


      - name: Dry dry
        run: cargo run -- --plan tests/fixtures/out.json --modules tests/fixtures/modules.json --module-root simulator/modules --dry-run
#
#      - name: Run just plan
#        run: just plan
#
#      - name: Run entrypoint test
#        run: |
#          chmod +x entrypoint.sh
#          ./test/entrypoint_test.sh

