name: Test Import Script

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-import-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Set up Shell Test Env
        run: sudo apt-get install -y jq

      - name: Setup terragrunt
        uses: metro-digital/cf-github-actions/terragrunt-setup@v1

      - name: Just install
        uses: extractions/setup-just@v3
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Run just init
        run: just init

      - name: Run just plan
        run: just plan

      - name: Run entrypoint test
        run: |
          chmod +x entrypoint.sh
          ./test/entrypoint_test.sh

